### PR TITLE
Fix missing DAYS_IN_COUNTRY

### PR DESCRIPTION
**Pull request by breakertt**

### CODE REVIEW

**Comment by estebangc98** [comment]
Were you able to reschedule an appointment with this modification?

**Comment by breakertt** [comment]
> Were you able to reschedule an appointment with this modification?

Yes, you also need to change `Continuar` in the following line
```
REGEX_CONTINUE = "//a[contains(text(),'Continuar')]"
```
to `Continue` if you visa website is using English

**Comment by estebangc98** [comment]
Didn't worked for me, just says "Reschedule failed".

**Comment by uxDaniel** [comment]
Thanks again, @breakertt!

**Pull request merged**
