### PR TITLE
Update to match latest version of appointment form

### PR DESCRIPTION
**Pull request by orendon**
I ran the script today and it was failing to reschedule, also I noticed the appointment form differs from the fields in the script, so I fixed it accordingly.

I was able to get an earlier appointment (from July to October) using this fix 🎉

Related to #7

### CODE REVIEW

**Comment by uxDaniel** [comment]
Hello @orendon! Thanks a lot for taking the time to submit a fix.
Just out of curiosity, wouldn't this change make the scheduler work for the ASC appointments (biometrics, etc) instead of the Consulate one (interview, leave passport)?

**Comment by orendon** [comment]
@uxDaniel You might be right, I was required an interview in the past but not this time, so I'm not aware of the other kind of appointments.
Prolly better to hold this PR until we do some further investigation, as this might be tailored to my specific use case

**Comment by juanzgc** [comment]
@uxDaniel Currently, is the scheduler providing appointments for ASC appointments and Consulate or at the moment is it only providing appointments for Consulate? It seems that the facility id is set to `25` which is only Consulate. Should I create a PR that checks if a reschedule requires both a Consulate and ASC update? 

ASC = 26
Consulate = 25

It seems this PR had the right idea, of attempting to reschedule both. https://github.com/uxDaniel/visa_rescheduler/pull/2

**Comment by uxDaniel** [comment]
Absolutely, please go for it and we can review the PR. Thank you!

**Pull request closed without merging**
